import type { Metadata } from "next";
import "./globals.css";
import { PT_Sans_Narrow, Noto_Sans_JP, Caveat } from "next/font/google";

const narrow = PT_Sans_Narrow({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-narrow",
});
const noto = Noto_Sans_JP({
  weight: "300",
  subsets: ["latin"],
  variable: "--font-noto",
});
const notoWeight = Noto_Sans_JP({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-noto",
});
const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body
        className={`${narrow.variable} ${noto.variable} ${notoWeight.variable} ${caveat.variable} font-noto`}>
        {children}
      </body>
    </html>
  );
}
