import { Metadata } from "next";
import "./globals.css";
import { GlobalLayout } from "@/components/layouts/GlobalLayout/GlobalLayout";

// NOTE: next/font/googleを利用したいが、現状では@storybook/react-webpack5では利用できないため、普通にimportして利用する
// import { PT_Sans_Narrow, Noto_Sans_JP, Caveat } from "next/font/google";
// const narrow = PT_Sans_Narrow({
//   weight: "400",
//   subsets: ["latin"],
//   variable: "--font-narrow",
// });
// const noto = Noto_Sans_JP({
//   weight: "400",
//   subsets: ["latin"],
//   variable: "--font-noto",
// });
// const notoWeight = Noto_Sans_JP({
//   weight: "700",
//   subsets: ["latin"],
//   variable: "--font-noto-weight",
// });
// const caveat = Caveat({
//   subsets: ["latin"],
//   variable: "--font-caveat",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`font-noto`}>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
}
