openapi: 3.0.0
info:
  title: ito - OpenAPI 3.0
  version: 1.0.0
tags:
  - name: Torisan
paths:
  /a/torisans:
    post:
      tags:
        - Torisan
      operationId: Torisan_register
      summary: 新しい鳥さんを登録する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.Torisan'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TorisanModel.Torisan'
components:
  schemas:
    TorisanModel.Torisan:
      type: object
      required:
        - nickname
        - birthDate
        - stage
      properties:
        nickname:
          type: string
        birthDate:
          type: string
        stage:
          type: number
          enum:
            - 1
            - 2
      description: 鳥さん
servers:
  - url: http://localhost:8080
    description: ''
    variables: {}
