openapi: 3.0.0
info:
  title: ito - OpenAPI 3.0
  version: 1.0.0
tags:
  - name: Torisan
paths:
  /a/torisans:
    get:
      tags:
        - Torisan
      operationId: Torisan_summary
      summary: 鳥さんの一覧情報を見る
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TorisanModel.SummaryTorisan'
    post:
      tags:
        - Torisan
      operationId: Torisan_register
      summary: 新しい鳥さんを登録する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TorisanModel.RegisterTorisan'
  /a/torisans/{id}:
    put:
      tags:
        - Torisan
      operationId: Torisan_update
      summary: 鳥さんの情報を更新する
      parameters:
        - name: id
          in: path
          required: true
          description: 鳥さんのID
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TorisanModel.UpdateTorisan'
    get:
      tags:
        - Torisan
      operationId: Torisan_detail
      summary: 鳥さんの情報詳細を見る
      parameters:
        - name: id
          in: path
          required: true
          description: 鳥さんのID
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
components:
  schemas:
    TorisanModel.DetailTorisan:
      type: object
      required:
        - id
        - stage
        - basic
        - objective
        - meal
      properties:
        id:
          type: integer
          format: int64
        stage:
          type: number
          enum:
            - 1
            - 2
            - 3
        basic:
          type: object
          properties:
            nickname:
              type: string
            birth_date:
              type: string
            species_id:
              type: integer
              format: int32
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
          required:
            - nickname
            - birth_date
            - species_id
            - gender_type
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
            amount_of_water:
              type: number
              format: float
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
          required:
            - staple_food_id
            - additional_food_ids
      description: 詳細用の鳥さん
    TorisanModel.RegisterTorisan:
      type: object
      required:
        - basic
        - objective
        - meal
      properties:
        basic:
          type: object
          properties:
            nickname:
              type: string
            birth_date:
              type: string
            species_id:
              type: integer
              format: int32
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
          required:
            - nickname
            - birth_date
            - species_id
            - gender_type
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
            amount_of_water:
              type: number
              format: float
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
          required:
            - staple_food_id
            - additional_food_ids
      description: 鳥さん
    TorisanModel.SummaryTorisan:
      type: object
      required:
        - id
        - status
        - basic
      properties:
        id:
          type: integer
          format: int64
        status:
          type: number
          enum:
            - 1
            - 2
            - 3
            - 2
            - 3
        basic:
          type: object
          properties:
            nickname:
              type: string
            birth_date:
              type: string
            species_id:
              type: integer
              format: int32
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
          required:
            - nickname
            - birth_date
            - species_id
            - gender_type
      description: サマリ用の鳥さん
    TorisanModel.UpdateTorisan:
      type: object
      required:
        - objective
        - meal
      properties:
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
            amount_of_water:
              type: number
              format: float
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
          required:
            - staple_food_id
            - additional_food_ids
      description: 更新用の鳥さん
servers:
  - url: http://localhost:8080
    description: ''
    variables: {}
