openapi: 3.0.0
info:
  title: ito - OpenAPI 3.0
  version: 1.0.0
tags:
  - name: Torisan
paths:
  /a/torisans:
    get:
      tags:
        - Torisan
      operationId: Torisan_summary
      summary: 鳥さんの一覧情報を見る
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TorisanModel.SummaryTorisan'
    post:
      tags:
        - Torisan
      operationId: Torisan_register
      summary: 新しい鳥さんを登録する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TorisanModel.RegisterTorisan'
  /a/torisans/species:
    get:
      tags:
        - Torisan
      operationId: Torisan_getTypes
      summary: 鳥さんの種類一覧を見る
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TorisanModel.TorisanSpecie'
  /a/torisans/{id}:
    put:
      tags:
        - Torisan
      operationId: Torisan_update
      summary: 鳥さんの情報を更新する
      parameters:
        - name: id
          in: path
          required: true
          description: 鳥さんのID
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TorisanModel.UpdateTorisan'
    get:
      tags:
        - Torisan
      operationId: Torisan_detail
      summary: 鳥さんの情報詳細を見る
      parameters:
        - name: id
          in: path
          required: true
          description: 鳥さんのID
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TorisanModel.DetailTorisan'
components:
  schemas:
    TorisanModel.DetailTorisan:
      type: object
      required:
        - id
        - nickname
        - stage
        - basic
        - objective
        - meal
      properties:
        id:
          type: integer
          format: int64
          description: ID
        nickname:
          type: string
          description: ニックネーム（システムの呼び名）
        stage:
          type: number
          enum:
            - 1
            - 2
            - 3
          description: ステージ
        basic:
          type: object
          properties:
            name:
              type: string
              description: 本名
            birth_date:
              type: string
              description: 誕生日
            species_id:
              type: integer
              format: int32
              description: 種類ID
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
              description: 性別
          required:
            - name
            - birth_date
            - species_id
            - gender_type
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
              description: 体重
            amount_of_water:
              type: number
              format: float
              description: 水の量
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
              description: 主食ID
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
              description: 副食IDリスト
          required:
            - staple_food_id
            - additional_food_ids
      description: 詳細用の鳥さん
    TorisanModel.RegisterTorisan:
      type: object
      required:
        - nickname
        - basic
        - objective
        - meal
      properties:
        nickname:
          type: string
          description: ニックネーム（システムの呼び名）
        basic:
          type: object
          properties:
            name:
              type: string
              description: 本名
            birth_date:
              type: string
              description: 誕生日
            species_id:
              type: integer
              format: int32
              description: 種類ID
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
              description: 性別
          required:
            - name
            - birth_date
            - species_id
            - gender_type
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
              description: 体重
            amount_of_water:
              type: number
              format: float
              description: 水の量
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
              description: 主食ID
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
              description: 副食IDリスト
          required:
            - staple_food_id
            - additional_food_ids
      description: 登録用の鳥さん
    TorisanModel.SummaryTorisan:
      type: object
      required:
        - id
        - nickname
        - stage
        - basic
      properties:
        id:
          type: integer
          format: int64
          description: ID
        nickname:
          type: string
          description: ニックネーム（システムの呼び名）
        stage:
          type: number
          enum:
            - 1
            - 2
            - 3
            - 2
            - 3
          description: ステージ
        basic:
          type: object
          properties:
            name:
              type: string
              description: 本名
            birth_date:
              type: string
              description: 誕生日
            species_id:
              type: integer
              format: int32
              description: 種類ID
            gender_type:
              type: number
              enum:
                - 1
                - 2
                - 3
                - 2
                - 3
              description: 性別
          required:
            - name
            - birth_date
            - species_id
            - gender_type
      description: サマリ用の鳥さん
    TorisanModel.TorisanSpecie:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: ID
        name:
          type: string
          description: 種類名
    TorisanModel.UpdateTorisan:
      type: object
      required:
        - objective
        - meal
      properties:
        objective:
          type: object
          properties:
            body_weight:
              type: number
              format: float
              description: 体重
            amount_of_water:
              type: number
              format: float
              description: 水の量
          required:
            - body_weight
            - amount_of_water
        meal:
          type: object
          properties:
            staple_food_id:
              type: integer
              format: int32
              description: 主食ID
            additional_food_ids:
              type: array
              items:
                type: integer
                format: int32
              description: 副食IDリスト
          required:
            - staple_food_id
            - additional_food_ids
      description: 更新用の鳥さん
servers:
  - url: http://localhost:8080
    description: ''
    variables: {}
